# 모듈과 클래스

## 복습

In [34]:
#복습1
#소수 판별 is_prime(), 입력값은 리스트[2,3.4,5.6,7,8,9]
def is_prime(num_list):
    ans = []
    for num in num_list:
        is_prime_num = True
        for i in range(2, num):
            if num%i==0:
                is_prime_num = False
                break
        ans.append(is_prime_num)
    return ans

In [35]:
is_prime([2,3,4,5,6,7,8,9])

[True, True, False, True, False, True, False, False]

In [ ]:
#복습2
#등수 구하기
def rank(score):
    print(score)
    # avg = [(i+j)/2 for i,j in score]
    avg = [sum(s)/len(s) for s in score]
    print(avg)
    sorted_avg = sorted(avg, reverse=True) #sort()를 하면 원본을 변형, 원래 리스트 순서대로 랭크를 넣을 수가 없음
    # ranks = [sorted_avg.index(a) + 1 for a in avg] #enumerate를 사용하는 것이 훨씬 빠름
    ranks = [list(enumerate(sorted_avg))[0][0] for a in avg]
    print('등수: ', ranks)
    return ranks

In [51]:
score = [[80, 70], [90, 50], [40, 70], [50, 80]]
avg = [(i+j)/2 for i,j in score]
print(avg)
sorted_avg = sorted(avg, reverse=True)
print(sorted_avg)
print(list(enumerate(sorted_avg))[0][0])
# ranks = [list(enumerate(sorted_avg))[a][0] for a in avg]

[75.0, 70.0, 55.0, 65.0]
[75.0, 70.0, 65.0, 55.0]
0


In [37]:
print('score1')
score1 = [[80, 70], [90, 50], [40, 70], [50, 80]]
rank(score1) # [1, 2, 4, 3]

print('score2')
score2 = [[80, 70], [70, 80], [30, 50], [90, 100], [100, 90], [100, 100], [10, 30]]
rank(score2) # [4, 4, 6, 2, 2, 1, 7]

score1
[[80, 70], [90, 50], [40, 70], [50, 80]]
[75.0, 70.0, 55.0, 65.0]
등수:  [1, 2, 4, 3]
score2
[[80, 70], [70, 80], [30, 50], [90, 100], [100, 90], [100, 100], [10, 30]]
[75.0, 75.0, 40.0, 95.0, 95.0, 100.0, 20.0]
등수:  [4, 4, 6, 2, 2, 1, 7]


[4, 4, 6, 2, 2, 1, 7]

In [41]:
arr = [[80, 70], [90, 50], [40, 70], [50, 80]]
# arr.index([80, 70])
for i, avg in enumerate(arr):
    print(i+1, avg)

1 [80, 70]
2 [90, 50]
3 [40, 70]
4 [50, 80]


## 모듈

In [52]:
import sys
for path in sys.path:
    print(path)

c:\Users\USER\AppData\Local\Programs\Python\Python311\python311.zip
c:\Users\USER\AppData\Local\Programs\Python\Python311\DLLs
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib
c:\Users\USER\AppData\Local\Programs\Python\Python311

C:\Users\USER\AppData\Roaming\Python\Python311\site-packages
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages


모듈과 기능 불러오는 방법 5가지

In [ ]:
# 1번
# 2번째 권장!
# 모듈 가져오기
import random 
random.randint(1,100) #1,100사이 정수 중 랜덤한 정수를 반환

#내장 함수는 import하거나 모듈이름을 써주지 않아도 됨 예)print()

43

In [ ]:
# 2번
#제일 권장!!
#Aliasing
import random as r #약어로 사용할 수 있음
r.randint(1,100)

91

In [ ]:
# 3번
# 특정 기능만 불러와서 사용 가능 (단, 해당 모듈의 다른 기능은 사용할 수 없음)
from random import randint 
randint(1,100)
# randrange(1,100) #에러 발생

15

In [ ]:
# 4번
# 한 모듈의 기능 여러 개를 한 번에 가져오기
from random import randint, randrange
randint(1,100)
randrange(1,100)

61

In [ ]:
# 5번
# 권장x
# random.randint() 이런식으로 모듈.메서드 모듈 이름 쓸 필요 없이 사용 가능
# 단, 모듈 간에 겹치는 이름이 있을 경우에는 에러가 발생할 수 있음 
# 가능한 구별 가능하도록 축약해서 모듈명 쓰는 것을 가장 권장
from random import *
randint(1,100)
randrange(1,100)
sample([1,2,3], 1)

### 사용자 정의 모듈

같은 디렉토리(더미 모듈용)에 mymodule.py 생성하기

In [64]:
# 생성한 mymodule.py불러오기
import mymodule as mm 
print(mm.my_add(8,5))
print(mm.my_sub(8,5))

13
3


if __name__ == "__main__": 
* 모듈 파일(.py) 테스트하기 위해 모듈 파일 내에 작성
* 이 아래에 테스트 코드 작성

In [66]:
# __name__ == "__main__" 추가하고 확인하기
import mymodule as mm 
print(mm.my_add(8,5))
print(mm.my_sub(8,5))

13
3


In [ ]:
#모듈로써 실행 vs py파일 실행인지 구분해보기
#원래는 커널 다시 시작해야 함. 
#주피터는 모듈을 한 번 메모리에 로드하면 매번 새롭게 불러오는 게 아니라
#캐싱된 모듈을 불러오기 때문에
#그래서 importlib 불러와서 reload해보기
import importlib 
importlib.reload(mm)

import mymodule as mm 
print(mm.my_add(8,5))

mymoudle안에서의 __name__:mymodule
13


In [86]:
# 미션
# 모듈 이용해 로또번호 추첨기 만들기
# [1,2,3,4,5,6,7]
import random as r

def lotto():
    lotto = []
    # for i in range(7): #중복이 있는 경우 7개보다 적게 뽑힐 수 있음
    #     num = r.randint(1,45)
    #     if num not in lotto:
    #         lotto.append(num) 
    
    while len(lotto) < 7:
        num = r.randint(1,45)
        if num not in lotto:
            lotto.append(num)

    print(lotto)

lotto()

[25, 35, 21, 4, 23, 32, 19]


In [90]:
# sample 함수 이용하기
# sample(범위, 개수) = 리스트
import random as r

def lotto():
    lotto = r.sample(range(1,46), 7)
    print(lotto)

lotto()

[6, 16, 37, 18, 34, 10, 7]


In [ ]:
# 미션2
# 컴퓨터와 대결하는 가위,바위,보 게임 만들기
import random
def checkwin(user, com):
    #user 인풋을 매핑
    

while True:
    #가위: 0, 바위: 1, 보: 2
    user = input("가위, 바위, 보 : ")
    com = sel[random.randint(0,2)]
    if checkWin(user,com): 
        if continueConfirm():
            continue
        else:
            break

## 클래스

* 클래스 = 붕어빵틀   객체 = 붕어빵
* 동작=메소드   속성=변수

In [103]:
#클래스 이름 첫글자는 대문자! 다른 메서드, 변수와 구분하기 위함
class Person: 
    def __init__(self, name, age):  #self:이스턴스 간 구분을 위함
        self.name = name
        self.age = age
    def walk(self):
        print(f'{self.name}이(가) 걸어가요')

In [104]:
person1 = Person('홍길동', 35)

In [105]:
type(person1)

__main__.Person

In [106]:
print(type(person1)) #print를 찍어야 클래스라고 출력됨

<class '__main__.Person'>


In [107]:
person2 = Person('김영희', 28)

In [108]:
person2.walk()

김영희이(가) 걸어가요


### 상속

In [ ]:
class NewPerson(Person): # Person 클래스를 상속 
    # pass
    # 1. 기능확장
    def fly(self):
        print(f'{self.name}이 하늘을 날아요')
    # 2. 메서드 오버라이딩 : 같은 이름의 상속 받은 매서드를 재정의
    def walk(self):
        print(f'{self.name}이(가) 아주 빠르게 걸어가요')
    

In [121]:
# 상속 받은 하위 클래스는 상위 클래스의 속성, 메서드를 상속 받아 사용할 수 있음 
person3 = NewPerson('김영광', 35)
person3.walk()
print(person3.age)

김영광이(가) 걸어가요
35


In [124]:
person3.fly()

김영광이 하늘을 날아요


In [133]:
class NewNewPerson(Person): # Person 클래스를 상속 
    # 4. 클래스 변수
    population = 0

    # 3. 오버로딩 : 
    def __init__(self, name, age, hobby): 
       super().__init__(name, age)  #부모 클래스에서 정의된 필드를 그대로 가져옴
       self.hobby = hobby
       # 4. 클래스 변수
       NewNewPerson.population += 1

    def fly(self):
        print(f'{self.name}이 하늘을 날아요')

    def walk(self):
        print(f'{self.name}이(가) 아주 빠르게 걸어가요')
        
    # 3. 오버로딩 
    def introduce(self):
        print(f'{self.name}의 취미는 {self.hobby}입니다')

In [134]:
person4 = NewNewPerson('김남길', 45, "운동하기")

In [129]:
person4.hobby

'운동하기'

In [130]:
person4.introduce()

김남길의 취미는 운동하기입니다


In [135]:
# 4. 클래스 변수 
person5 = NewNewPerson('김남길', 45, "운동하기")
person6 = NewNewPerson('수지', 32, "운동하기")
person7 = NewNewPerson('김태희', 45, "운동하기")

In [ ]:
#같은 클래스의 모든 객체가 같은 값을 가짐
print(person5.population)
print(person6.population)
print(person7.population)

4
4
4


## python turtle
-> .py에서 실행하는 것이 더 안정적. turtleTest.py로 이동

## Numpy

In [141]:
# % 을 입력하면 터미널처럼 명령어를 통해 모듈 설치 가능 
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.6/12.6 MB 12.2 MB/s eta 0:00:01
   ---- ----------------------------------- 1.3/12.6 MB 13.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.7/12.6 MB 18.9 MB/s eta 0:00:01
   ------------ --------------------------- 4.0/12.6 MB 21.4 MB/s eta 0:00:01
   ----------------- ---------------------- 5.6/12.6 MB 23.8 MB/s eta 0:00:01
   ---------------------- ----------------- 7.0/12.6 MB 24.6 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 25.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.9/12.6 MB 26.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 29.8 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 31.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 28.4 MB/s eta 0:00:00


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [142]:
import numpy as np #보통 np라고 쓴다

In [143]:
np.__version__

'2.4.0'

In [146]:
# 파이썬 리스트 : 요소가 , 로 구분됨
alist = [1,2,3,4,5]
print(alist)
print(type(alist))

[1, 2, 3, 4, 5]
<class 'list'>


In [149]:
#파이썬 리스트 -> 넘파이 배열
# , 가 아닌 공백으로 요소를 구분
ar1 = np.array(alist)
print(ar1)
print(type(ar1))
# ndarray = n dimensional array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [155]:
# 어레이.dtype : 넘파이 배열 안에 저장된 데이터의 타입 확인 
print(ar1.dtype) #int64

# 정수, 실수 섞이면 데이터타입이 실수(float)로 결정됨 
ar2 = np.array([1, 1.5, 2.0])
ar2.dtype # dtype('float64')
print(ar2) # 1 -> 1. 실수로 찍힘

int64
[1.  1.5 2. ]


In [198]:
various_dtype = np.array([ 1, '2', 3.0])
various_dtype
# 문자열 섞여 있으면 문자열로 통일됨 
# 더 큰 데이터 타입으로 통일

array(['1', '2', '3.0'], dtype='<U32')

In [ ]:
# 넘파이배열.ndim : 차원(int)
ar1.ndim

1

In [ ]:
# 넘파이배열.shape : 크기(tuple)
ar1.shape 
#(5, ) : ,를 붙여서 튜플 형태로 크기?를 출력해줌 (,없으면 튜플로 인식이 안되므로)

(5,)

In [160]:
ar3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
print(ar3.shape)
print(ar3.ndim)

(3, 4)
2


In [ ]:
# 배열.reshape(행 즉 세로, 열 즉 가로) = 바뀐 모양의 넘파이 배열
ar3.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [168]:
# 만약 개수가 맞지 않으면 ValueError발생
# 하나만 지정하고, 나머지를 -1로 지정하면 자동으로 행 또는 열 개수가 계산됨
print(ar3.reshape(4, -1))
print(ar3.reshape(-1, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [177]:
# 3차원으로 모양 지정
ar4 = ar3.reshape(2,-1,3) 

In [178]:
#[[[ ]]] 3개 이므로 3차원
print(ar4.ndim)
print(ar4.shape)

3
(2, 2, 3)


np.arange(시작값, 끝값, 간격) = 넘파이 배열 즉 어레이 
* 단, 끝값은 미만, 포함 안 됨

In [181]:
# np.arange(시작값, 끝값) = 넘파이 배열 즉 어레이 
# 단, 끝값은 미만, 포함 안 됨
x = np.arange(1,10) 
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
y = np.arange(1, 10, 2)
y

array([1, 3, 5, 7, 9])

특별한 값을 갖는 넘파이 배열 생성

In [189]:
# 동일한 크기, 사이즈의 다른 넘파이배열을 만들 경우
# 1. 크기는 같은데 0으로 채워진 다른 배열 만들기 : np.zeros_like() = 0으로 채워진 같은 크기의 어레이
zerolike_arr = np.zeros_like(x)
zerolike_arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
zero_arr = np.zeros(10, dtype=int)
zero_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one_arr = np.ones(10) #마스킹
one_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [208]:
# 기본 행렬 eye
eye_arr = np.eye(5)
eye_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

공식 사이트 참조) https://numpy.org/

numpy 속도 확인하기

In [ ]:
# 순회하는데 시간 측정하기 
# time 활용
import time

# 리스트, 배열 생성
size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)

# 리스트 시간 측정 
start_time = time.time()
result_list = [ x*2 for x in py_list] #map을 쓰면 시간 단축 가능
end_time = time.time()
print(f'파이썬 리스트 : {end_time - start_time:.5f}초 소요됨') # 소수점 5번째 자리까지 측정

# 넘파이 배열 시간 측정
start_time = time.time()
result_array = np_arr * 2 #넘파이 연산 
end_time = time.time()
print(f'넘파이 배열 : {end_time - start_time:.5f}초 소요됨') # 소수점 5번째 자리까지 측정

파이썬 리스트 : 0.04271초 소요됨
넘파이 배열 : 0.00199초 소요됨


넘파이 배열 연산

In [202]:
a_arr = np.array([1,2,3,4,5])
b_arr = np.array([6,7,8,9,10])

# 리스트의 경우에는 두 리스트를 모두 각각 순회하여 새로운 리스트에 더해야 함
# 알아서 동일한 인덱스끼리 연산해줌**
a_arr + b_arr

array([ 7,  9, 11, 13, 15])

In [203]:
print(a_arr - b_arr)
print(a_arr * b_arr)
print(a_arr / b_arr)

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [205]:
#일괄적으로 모든 요소에 +1 
print(a_arr + 1) # 동일한 shape의 1을 가진 array와 계산
print(a_arr - 1) 
print(a_arr * 1) 
a_arr / 1

[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]


array([1., 2., 3., 4., 5.])

In [ ]:
# 연산 미션
# 1. 파이썬 리스트 데이터 모두 2배로 변경
data_list = [0,1,2,3,4,5,6,7,8,9]
cal_list = [x*2 for x in data_list]
cal_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# 연산 미션
# 2. 넘파이 배열 데이터 모두 2배로 변경
data_arr = np.array([0,1,2,3,4,5,6,7,8,9])
cal_arr = data_arr * 2  #내부에서는 for문 도는 것처럼, c코드로, 연산이 이루어짐
cal_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 도전하기 p.19
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2) #리스트는 통째로 비교, 하나의 대답만. 넘파이 배열은 요소마다 비교한 결과값을 어레이로 출력
print(b > 10)
print((a == 2) & (b > 10)) # and가 아닌 &를 사용해야 함

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


넘파이 어레이 인덱싱 및 슬라이싱

In [218]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [229]:
# 다음의배열에서0, 1, 5 값을뽑아내주세요
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0][0])
print(a[0][1])
print(a[1][2])
# array는 대괄호 생략 가능 
print(a[0,1])

0
1
5
1


In [233]:
#리스트의 경우에는 
list_indexing = [[0, 1, 2], [3, 4, 5]]
list_indexing[0][1]
# list_indexing[0,1] #리스트에서는 이렇게는 작동하지 않음 

1

In [220]:
# 다음의배열에서 [0, 1, 2] 값을뽑아내주세요
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0])

[0 1 2]


In [236]:
# 다음의 배열에서 아래 부분을 뽑아내주세요 1과 5
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[:,1])

[1 5]


In [ ]:
# 다음의 배열에서 아래 부분을 뽑아내주세요 5,6,7
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[1,1:])

[5 6 7]


In [238]:
# 다음의 배열에서 아래 부분을 뽑아내주세요 0,1,4,5
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[:,:2])

[[0 1]
 [4 5]]


팬시 인덱싱(fancy indexing)
* 위치 정보를 나타내는 다른 ndarray 배열
* 종류 : boolean 배열 / 정수 배열 

1. boolean 방식

In [252]:
#1. boolean 방식 팬시 인덱싱
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]
# 만약에 boolean 인덱스 배열의 크기가 다르면 IndexError가 발생
# 모든 요소의 존재 여부를 가지고 있어야 함

array([0, 2, 4, 6, 8])

In [249]:
# 조건문 연산을 사용하여 짝수 인원인 원소만 골라내기
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 인덱스 비교 연산자 결과는 각 요소들을 비교한 T/F가 array로 출력됨
# idx = (a % 2==0) 
# a[idx]
a[a % 2 == 0] # 짧은 버전

array([0, 2, 4, 6, 8])

2. 정수 방식

In [254]:
# 2. 정수 방식 팬시 인덱싱
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]
# 필요한 원소의 인덱스만 정수 형태로 가지고 있으면 됨
# 개수를 맞출 필요는 없음

array([11, 33, 55, 77, 99])

In [255]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
print(a[idx])

[11 11 11 11 11 11 22 22 22 22 22 33 33 33 33 33]


In [ ]:
# p.36
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[ : , [0,3] ]
# a[ : , [True, False, False, True] ]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
# p.37
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[ [2,0,1] , :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [273]:
# p.38
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 1. 배열에서 3의 배수를 찾아주세요
mul3 = x[x % 3 ==0]
# 2. 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
mul4 = x[x % 4 == 1]
# 3. 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.
mul3and4 = x[(x % 3 ==0) & (x % 4 == 1)]

print('Answer:')
print('1. ', mul3)
print('2. ', mul4)
print('3. ', mul3and4)

Answer:
1.  [ 3  6  9 12 15 18]
2.  [ 1  5  9 13 17]
3.  [9]


flatten

In [274]:
b = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5]],
               [[ 6,  7],
                [ 8,  9],
                [10, 11]]])
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 벡터화 연산

In [275]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = x + y
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

시간 비교

In [282]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 4.44 ms


In [ ]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [284]:
# 비교하기
## 요소 1개씩 비교
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)
print(a >= b)

[False  True False  True]
[False  True  True  True]


In [285]:
# 비교하기
## 전체 비교하기

In [286]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(np.all(a == b))
print(np.all(a >= b))

False
False


유니버셜 함수) 기본 통계 함수들
* 합계: arr.sum()
* 최댓값, 최솟값: arr.max(), arr.min()
* 최댓값, 최솟값의 인덱스 반환: arr.argmax(), arr.argmin()
* 평균: arr.mean()

In [288]:
x = np.array([1, 2, 3, 4])
print( '합: ', x.sum() )
print( '최솟값: ', x.min() )
print( '최솟값 인덱스: ', x.argmin() )
print( '평균: ', x.mean() )

합:  10
최솟값:  1
최솟값 인덱스:  0
평균:  2.5
